site_name: Whizzbang
theme: 'readthedocs'
markdown_extensions:
  - toc:
      permalink: True
extra:
  palette:
      primary: '#087da1'
      accent: '#00a889'
  social:
    - type: 'github'
      link: 'https://github.com/drajen'
    - type: 'twitter'
      link: 'https://twitter.com/datamattsson'
repo_name: 'drajen/whizzbang'
repo_url: 'https://github.com/drajen/whizzbang'
copyright: 'Copyright © 2020 <a href="https://datamattsson.io">Data Mattsson</a>'
google_analytics:
  - 'UA-79554149-3'
  - 'auto'
nav:
  - Home: 'index.md'
  - Installation:
      - 'Getting started': 'installation/gettingstarted.md'
  - Contributing:
      - 'General':  'contributing.md'
  - FAQ: 'faq.md'
