site_name: Whizzbang
site_url: 'https://whizzbang.datamattsson.io'
theme: 'readthedocs'
repo_name: 'drajen/whizzbang'
repo_url: 'https://github.com/drajen/whizzbang'
copyright: 'Copyright © 2020 <a href="https://datamattsson.io">Data Mattsson</a>'
extra_css:
  - css/hpedev.css
google_analytics:
  - 'UA-79554149-3'
  - 'https://whizzbang.datamattsson.io'
nav:
  - HOME: 'index.md'
  - INSTALLATION:
    - 'Getting started': 'installation/getting_started.md'
  - DRIVERS:
    - Soap: 'soap.md'
    - Schampoo: 'soap.md'
  - USE CASES:
    - Wash Cars: 'cars.md'
    - Run to errands around town: 'usecase2.md'
    - This is a very long thing to do as we love long names: 'long.md'
  - CONTRIBUTING: 'contributing.md'
  - FAQ: 'faq.md'
  - Markdown sandbox: 'sample.md'
